### ISSUE TITLE
Updated data

### ISSUE THREAD

**Issue by smasher35** [onidivo/actors-covid-19#26]
The data doesn't get updated for about five days, still the same stats

**Comment by remyoucef** [comment]
For which country?

**Comment by smasher35** [comment]
Portugal 🇵🇹

A sexta, 10/04/2020, 18:22, Youcef Islam Remichi <notifications@github.com>
escreveu:

**Comment by remyoucef** [comment]
Portugal actor failed just today (2020-04-10 13:50:02) and we're fixing it
https://api.apify.com/v2/key-value-stores/BXGEYTTUQzYBboEQK/records/LATEST?disableRedirect=true

Where did you find that the data doesn't get updated for about five days?

**Comment by remyoucef** [comment]
I find the problem the links for the data wasn't updated here
https://github.com/apifytech/apify-docs/blob/master/ext/covid_api_list.json
I updated the links there, the new changes should be merged soon.

**Comment by smasher35** [comment]
Hi thanks

it's working now

[image: image.png]
Paulo Penicheiro
___
www.500px.com/paulopenicheiro

**Comment by remyoucef** [comment]
You're welcome! Thanks for reporting.
